server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
spring:
  application:
    name: feign_consumer
